---
title: "LME4 Test"
author: "Matthew Donaldson"
date: '2022-04-03'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(caret)
library(car)
library(olsrr)
library(lme4)
library(shiny)
library(cvms)
library(groupdata2)   # fold() partition()
library(knitr)        # kable()
library(dplyr)        # %>% arrange()
library(ggplot2)
```

```{r}
# Importing the data set and printing the first 6 rows to see what it looks like
asthmaDataOriginal = read.csv("Asthma_Data_File.csv") %>%
   rename(subj = UserNo.,
          loc = Location,
          age = Age,
          gender = Gender,
          odj = OutdoorJob,
          oda = OutdoorActivities,          
          sh = SmokingHabit,
          hum = Humidity,
          pres = Pressure,
          temp = Temperature,
          uv = UVIndex,
          ws = WindSpeed,
          score = ACTScore)
  
#  mutate(subj = factor(subj, levels = c(0:9), labels = c("1","2","3","4","5","6","7","8","9","10")),
#        loc = factor(loc, levels = c(0:5), labels = c("Petaling","Kampong Baharu         Balakong","Putrajaya","Kota Bharu","Kuala Lampur","Cyberjaya")),
#        age = factor(age, levels = c(0:3), labels = c("Above 50","41-50","31-40","19-30")),
#        gender = factor(gender, levels = c(0,1), labels = c("Male","Female")),
#        odj = factor(odj, levels = c(0,1,2), labels = c("Frequently","Occasionally","Rarely")),
#        oda = factor(oda, levels = c(0,1,2), labels = c("Extremely likely","Neither likely or dislikely","Not at all likely")),
#        sh = factor(sh, levels = c(0,1), labels = c("Yes", "No")),
#        uv = factor(uv, levels = c(0,1), labels = c("Extreme", "Low")))

head(asthmaDataOriginal)
```

Factoring
```{r}
asthmaData = asthmaDataOriginal

names = names(asthmaData[,c(1:8,10,12)]) 
asthmaData[,names] = lapply(asthmaData[,names], factor)

str(asthmaData)
```

```{r}

asthmaData$age = factor(asthmaData$age, levels = c(0:3), labels = c("Above 50","41-50","31-40","19-30"))

```



```{r}
set.seed(7)

# Fold data 
asthmaData = fold(data = asthmaData, k = 3,
            id_col = 'subj',num_fold_cols = 1,handle_existing_fold_cols = "keep") %>% 
            arrange(.folds)

asthmaData %>% head(15) %>% kable()
```


```{r}
# Cat to numerical output look at anova.
# Look at corr for continuous


### Note: for some reason age is a problem in this
mixed_model_formulas <- c("score ~ 1",
                          "score ~ (1|subj)",
                          "score ~ (1|loc)",
                          "score ~ temp + hum + (1|subj) + (1|loc)",
                          "score ~ temp + hum  + gender + (1|subj) + (1|loc)",
                          "score ~ temp + hum  + uv + (1|subj) + (1|loc)",
                          "score ~ temp + hum  + uv + ws + (1|subj) + (1|loc)",
                          "score ~ temp + hum  + uv + ws + gender + (1|subj) + (1|loc)",
                          "score ~ temp + hum  + uv + ws + gender + odj + (1|subj)")


CV <- cross_validate(data = asthmaData,
  formulas = mixed_model_formulas,
  fold_cols = '.folds',
  family = 'gaussian',
  REML = FALSE,
  preprocessing = "standardize")
```


```{r}
CV$Coefficients
par(mfrow=c(1,2))
plot(CV$RMSE)
plot(CV$AIC)
plot(CV$MAE)
```

```{r}
### Note: for some reason age is a problem in this
mixed_model_formulas <- c("score ~ 1",
                          "score ~ (1|subj)",
                          "score ~ (1|loc)",
                          "score ~ temp + (1|loc)",
                          "score ~ hum + (1|loc)",
                          "score ~ pres + (1|loc)",
                          "score ~ gender + (1|loc)",
                          "score ~ uv + (1|loc)",
                          "score ~ ws + (1|loc)")


CV <- cross_validate(data = asthmaData,
  formulas = mixed_model_formulas,
  fold_cols = '.folds',
  family = 'gaussian',
  REML = FALSE,
  preprocessing = "standardize")

par(mfrow=c(1,2))
plot(CV$RMSE)
plot(CV$AIC)
```



```{r}

library("lattice")
library("merTools")

bestModel = lmer(score ~ temp + hum  + uv + ws + gender + (1|subj) + (1|loc), data = asthmaData)


#summary(bestModel)
#dotplot(ranef(bestModel, condVar = TRUE))

preds = predictInterval(bestModel, n.sims = 500, level = 0.9, stat = 'median')
#head(preds)

```


```{r}

plot(bestModel, subj ~ resid(.), abline = 0 ) # generate diagnostic plots
plot(bestModel, loc ~ resid(.), abline = 0 ) # generate diagnostic plots

plot(bestModel, resid(., type = "pearson") ~ fitted(.) | subj, id = 0.05, 
     adj = -0.3, pch = 20, col = "gray40", cex = .5)

plot(bestModel, resid(., type = "pearson") ~ fitted(.) | loc, id = 0.05, 
     adj = -0.3, pch = 20, col = "gray40", cex = .5)

```


```{r}

# Kolmogorac- smrnov test  
library(influence.ME) # To get cooks distance
#par(mfrow=c(1,2))

plot(fitted(bestModel),residuals(bestModel))
#lines(lowess(fitted(bestModel), residuals(bestModel), col=2)

qqnorm(residuals(bestModel))
qqline(residuals(bestModel))

# Attempt at Cook's Distance, Crashed computer
#infl <- influence(bestModel, obs = TRUE)
#cooks.distance(infl)
#plot(infl, which = "cook")

# Prediction interval per subject
#preds[which(asthmaData$subj == 1),1]
#preds[which(asthmaData$subj == 2),]
#preds[which(asthmaData$subj == 3),]
#preds[which(asthmaData$subj == 4),]
#preds[which(asthmaData$subj == 5),]
#preds[which(asthmaData$subj == 6),]
#preds[which(asthmaData$subj == 7),]
#preds[which(asthmaData$subj == 8),]
#preds[which(asthmaData$subj == 9),]
#preds[which(asthmaData$subj == 10),]


```


```{r}

sjPlot::tab_model(bestModel)

```






Code Below is an example used to help with writing it for ours.
Link :https://cran.r-project.org/web/packages/cvms/readme/README.html#cross-validate-mixed-effects-models
```{r}

mixed_model_formulas <- c("score ~ diagnosis + (1|session)",
                          "score ~ age + (1|session)",
                          "score ~ diagnosis + (1|session)",
                          "score ~ age + (1|session)")

CV4 <- cross_validate(
  data = data,
  formulas = mixed_model_formulas,
  fold_cols = '.folds',
  family = 'gaussian',
  REML = FALSE
)

CV4
```












